template-file-path: webserver.yaml
parameters:
  - parameter-key: KeyPairName
    parameter-value: jinshuoji@keypair
  - parameter-key: VpcId
    parameter-value: vpc-097b82126e0f90dab
  - parameter-key: PublicSubnetId
    parameter-value: subnet-0e3acaf5108088fc1
tags:
  - tag-key: Environment
    tag-value: dev
